" Generated by vim-plug
" 30/1/2024 11:27:55 am
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['auto-pairs'].commit = '39f06b873a8449af8ff6a3eee716d3da14d63a76'
silent! let g:plugs['ctrlp.vim'].commit = '7c972cb19c8544c681ca345c64ec39e04f4651cc'
silent! let g:plugs['targets.vim'].commit = '642d3a4ce306264b05ea3219920b13ea80931767'
silent! let g:plugs['tcomment_vim'].commit = 'b4930f9da28647e5417d462c341013f88184be7e'
silent! let g:plugs['undotree'].commit = '0e11ba7325efbbb3f3bebe06213afa3e7ec75131'
silent! let g:plugs['vim-buftabline'].commit = '73b9ef5dcb6cdf6488bc88adb382f20bc3e3262a'
silent! let g:plugs['vim-cursorword'].commit = '371fdd7fa8817c28aa09d181cfcfa3c7ca29bf56'
silent! let g:plugs['vim-mucomplete'].commit = '03bcd4a7dfe0a2f6d432e8ce936d35273a15209d'
silent! let g:plugs['vim-polyglot'].commit = 'bc8a81d3592dab86334f27d1d43c080ebf680d42'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'

PlugUpdate!

