" Generated by vim-plug
" Wed 11 Mar 2026 03:41:03 PM
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['auto-pairs'].commit = '39f06b873a8449af8ff6a3eee716d3da14d63a76'
silent! let g:plugs['ctrlp.vim'].commit = '86872f021c4e245e3c583054fda82fb820a2faee'
silent! let g:plugs['targets.vim'].commit = '6325416da8f89992b005db3e4517aaef0242602e'
silent! let g:plugs['undotree'].commit = '6fa6b57cda8459e1e4b2ca34df702f55242f4e4d'
silent! let g:plugs['vim-buftabline'].commit = '6cdb6ae69a0dbccbed5683adfe79be810df6d661'
silent! let g:plugs['vim-cursorword'].commit = '371fdd7fa8817c28aa09d181cfcfa3c7ca29bf56'
silent! let g:plugs['vim-mucomplete'].commit = '7ad72b26aa679a6dda3837441742b7bd95eed3eb'
silent! let g:plugs['vim-polyglot'].commit = 'f061eddb7cdcc614c8406847b2bfb53099832a4e'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim9-stargate'].commit = 'b87f9e6f534de5cc261205f6fc7716ec1af28e3a'

PlugUpdate!

