" Generated by vim-plug
" 18/9/2023 3:16:30 pm
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['auto-pairs'].commit = '39f06b873a8449af8ff6a3eee716d3da14d63a76'
silent! let g:plugs['ctrlp.vim'].commit = '7c972cb19c8544c681ca345c64ec39e04f4651cc'
silent! let g:plugs['minibufexpl.vim'].commit = 'ad72976ca3df4585d49aa296799f14f3b34cf953'
silent! let g:plugs['supertab'].commit = 'f0093ae12a9115498f887199809a6114659fc858'
silent! let g:plugs['targets.vim'].commit = '642d3a4ce306264b05ea3219920b13ea80931767'
silent! let g:plugs['tcomment_vim'].commit = 'b4930f9da28647e5417d462c341013f88184be7e'
silent! let g:plugs['undotree'].commit = '0e11ba7325efbbb3f3bebe06213afa3e7ec75131'
silent! let g:plugs['vim-css-color'].commit = '6cc65734bc7105d9677ca54e2255fcbc953ba6bf'
silent! let g:plugs['vim-cursorword'].commit = '371fdd7fa8817c28aa09d181cfcfa3c7ca29bf56'
silent! let g:plugs['vim-easymotion'].commit = 'b3cfab2a6302b3b39f53d9fd2cd997e1127d7878'
silent! let g:plugs['vim-polyglot'].commit = 'bc8a81d3592dab86334f27d1d43c080ebf680d42'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'

PlugUpdate!

